# Generated by Django 3.2.7 on 2021-09-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('league_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=200)),
                ('self', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('teams', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=200)),
                ('self', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('times_trained', models.IntegerField()),
                ('league', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('self', models.CharField(max_length=200)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.ligas'),
        ),
    ]
